In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

Matplotlib is building the font cache; this may take a moment.

In [5]:
beneficiary_df = pd.read_csv("../data/raw/train/Train_Beneficiarydata-1542865627584.csv")

inpatient_df = pd.read_csv("../data/raw/train/Train_Inpatientdata-1542865627584.csv")

outpatient_df = pd.read_csv("../data/raw/train/Train_Outpatientdata-1542865627584.csv")

provider_df = pd.read_csv("../data/raw/train/Train-1542865627584.csv")

In [6]:
print("SHAPES")
print("Beneficiary:", beneficiary_df.shape)
print("Inpatient:", inpatient_df.shape)
print("Outpatient:", outpatient_df.shape)   
print("Provider:", provider_df.shape)

SHAPES
Beneficiary: (138556, 25)
Inpatient: (40474, 30)
Outpatient: (517737, 27)
Provider: (5410, 2)

In [11]:

beneficiary_df.columns.tolist()

['BeneID',
 'DOB',
 'DOD',
 'Gender',
 'Race',
 'RenalDiseaseIndicator',
 'State',
 'County',
 'NoOfMonths_PartACov',
 'NoOfMonths_PartBCov',
 'ChronicCond_Alzheimer',
 'ChronicCond_Heartfailure',
 'ChronicCond_KidneyDisease',
 'ChronicCond_Cancer',
 'ChronicCond_ObstrPulmonary',
 'ChronicCond_Depression',
 'ChronicCond_Diabetes',
 'ChronicCond_IschemicHeart',
 'ChronicCond_Osteoporasis',
 'ChronicCond_rheumatoidarthritis',
 'ChronicCond_stroke',
 'IPAnnualReimbursementAmt',
 'IPAnnualDeductibleAmt',
 'OPAnnualReimbursementAmt',
 'OPAnnualDeductibleAmt']

In [ ]:
print("\nadmitted in hospital:")
inpatient_df.columns.tolist()

admitted in hospital:
visits to hospital:
provider data:

['Provider', 'PotentialFraud']

In [23]:
print("visits to hospital:")
outpatient_df.columns.tolist()

visits to hospital:

['BeneID',
 'ClaimID',
 'ClaimStartDt',
 'ClaimEndDt',
 'Provider',
 'InscClaimAmtReimbursed',
 'AttendingPhysician',
 'OperatingPhysician',
 'OtherPhysician',
 'ClmDiagnosisCode_1',
 'ClmDiagnosisCode_2',
 'ClmDiagnosisCode_3',
 'ClmDiagnosisCode_4',
 'ClmDiagnosisCode_5',
 'ClmDiagnosisCode_6',
 'ClmDiagnosisCode_7',
 'ClmDiagnosisCode_8',
 'ClmDiagnosisCode_9',
 'ClmDiagnosisCode_10',
 'ClmProcedureCode_1',
 'ClmProcedureCode_2',
 'ClmProcedureCode_3',
 'ClmProcedureCode_4',
 'ClmProcedureCode_5',
 'ClmProcedureCode_6',
 'DeductibleAmtPaid',
 'ClmAdmitDiagnosisCode']

In [24]:
print("provider data:")
provider_df.columns.tolist()

provider data:

['Provider', 'PotentialFraud']

In [26]:
provider_df.head()

   Provider PotentialFraud
0  PRV51001             No
1  PRV51003            Yes
2  PRV51004             No
3  PRV51005            Yes
4  PRV51007             No

In [28]:
beneficiary_df.head(2)

,BeneID,DOB,DOD,Gender,Race,RenalDiseaseIndicator,State,County,NoOfMonths_PartACov,NoOfMonths_PartBCov,...,ChronicCond_Depression,ChronicCond_Diabetes,ChronicCond_IschemicHeart,ChronicCond_Osteoporasis,ChronicCond_rheumatoidarthritis,ChronicCond_stroke,IPAnnualReimbursementAmt,IPAnnualDeductibleAmt,OPAnnualReimbursementAmt,OPAnnualDeductibleAmt
0,BENE11001,1943-01-01,NaN,1,1,0,39,230,12,12,...,1,1,1,2,1,1,36000,3204,60,70
1,BENE11002,1936-09-01,NaN,2,1,0,39,280,12,12,...,2,2,2,2,2,2,0,0,30,50

In [29]:
inpatient_df.head(2)

,BeneID,ClaimID,ClaimStartDt,ClaimEndDt,Provider,InscClaimAmtReimbursed,AttendingPhysician,OperatingPhysician,OtherPhysician,AdmissionDt,...,ClmDiagnosisCode_7,ClmDiagnosisCode_8,ClmDiagnosisCode_9,ClmDiagnosisCode_10,ClmProcedureCode_1,ClmProcedureCode_2,ClmProcedureCode_3,ClmProcedureCode_4,ClmProcedureCode_5,ClmProcedureCode_6
0,BENE11001,CLM46614,2009-04-12,2009-04-18,PRV55912,26000,PHY390922,NaN,NaN,2009-04-12,...,2724,19889,5849,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,BENE11001,CLM66048,2009-08-31,2009-09-02,PRV55907,5000,PHY318495,PHY318495,NaN,2009-08-31,...,NaN,NaN,NaN,NaN,7092.0,NaN,NaN,NaN,NaN,NaN

In [30]:
outpatient_df.head(2)

,BeneID,ClaimID,ClaimStartDt,ClaimEndDt,Provider,InscClaimAmtReimbursed,AttendingPhysician,OperatingPhysician,OtherPhysician,ClmDiagnosisCode_1,...,ClmDiagnosisCode_9,ClmDiagnosisCode_10,ClmProcedureCode_1,ClmProcedureCode_2,ClmProcedureCode_3,ClmProcedureCode_4,ClmProcedureCode_5,ClmProcedureCode_6,DeductibleAmtPaid,ClmAdmitDiagnosisCode
0,BENE11002,CLM624349,2009-10-11,2009-10-11,PRV56011,30,PHY326117,NaN,NaN,78943,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,56409
1,BENE11003,CLM189947,2009-02-12,2009-02-12,PRV57610,80,PHY362868,NaN,NaN,6115,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,79380

#How are these four datasets connected?

In [31]:
#PROVIDER ID CONNECTS ALL DATASETS PROVIDER ID ->INPATIENT/OUTPATIENT -> BENEFICIARY

print("Provider ID connects all datasets: Provider ID -> Inpatient/Outpatient -> Beneficiary")

print(provider_df['Provider'].head())
print(inpatient_df['Provider'].head())
print(outpatient_df['Provider'].head())

Provider ID connects all datasets: Provider ID -> Inpatient/Outpatient -> Beneficiary
0    PRV51001
1    PRV51003
2    PRV51004
3    PRV51005
4    PRV51007
Name: Provider, dtype: str
0    PRV55912
1    PRV55907
2    PRV56046
3    PRV52405
4    PRV56614
Name: Provider, dtype: str
0    PRV56011
1    PRV57610
2    PRV57595
3    PRV56011
4    PRV56011
Name: Provider, dtype: str

In [32]:
print("bene ID connects inpatient and outpatient datasets: Bene ID -> Inpatient/Outpatient")

print(inpatient_df['BeneID'].head())
print(outpatient_df['BeneID'].head())
print(beneficiary_df['BeneID'].head())

bene ID connects inpatient and outpatient datasets: Bene ID -> Inpatient/Outpatient
0    BENE11001
1    BENE11001
2    BENE11001
3    BENE11011
4    BENE11014
Name: BeneID, dtype: str
0    BENE11002
1    BENE11003
2    BENE11003
3    BENE11004
4    BENE11004
Name: BeneID, dtype: str
0    BENE11001
1    BENE11002
2    BENE11003
3    BENE11004
4    BENE11005
Name: BeneID, dtype: str


#checking how many unique IDs exist

In [33]:
print("unique providers\n")

print("Provider:", provider_df['Provider'].nunique())
print("Inpatient:", inpatient_df['Provider'].nunique())
print("Outpatient:",outpatient_df['Provider'].nunique())

unique providers

Provider: 5410
Inpatient: 2092
Outpatient: 5012

In [34]:
print("unique bene IDs in inpatient and outpatient datasets:")
print("Inpatient:", inpatient_df['BeneID'].nunique())
print("Outpatient:", outpatient_df['BeneID'].nunique()) 
print("Beneficiary:", beneficiary_df['BeneID'].nunique())

unique bene IDs in inpatient and outpatient datasets:
Inpatient: 31289
Outpatient: 133980
Beneficiary: 138556